insert into course(vehicle_type, num_of_less) values ('Manual car', 28);
insert into course(vehicle_type, num_of_less) values ('Automatic car', 28);
delete from lector where id=2;
delete from course where id=4;
delete from student where id=7;
delete from sides where id=2;
delete from timetable where lesson_num = 4;

delete from student_course_lec where student_id = 7;
-- alter table course modify vehicle_type varchar(45) null unique;
select * from lector;
select * from course;
select * from student;
select * from sides;
select * from student_course_lec;
select * from timetable;
use drive_sch_db;
UPDATE student SET password = "1234" where email = 'adam@deb';
UPDATE lector SET verify_lector = "1234" where email = 'jan@pako';
UPDATE student SET verify_student = "1234" where email = 'ode2@seznam.cz';
desc student;
insert into lector(name, surname, email, verify_lector, phone_number, possicion, prefer_veh) values ('Jirka', 'Šunka', 'jirka@sunka', '132', '420000111222', 'admin', '2');
use drive_sch_db;
delete from course where id = 3;
SELECT * FROM timetable ORDER BY lesson_date, lesson_num;
alter table timetable modify lesson_date date NULL;
desc timetable;
desc student_course_lec;
select * from timetable;
insert into student_course_lec(student_id, course_id, lector_id) values(6, 1, 3);
insert into timetable(lesson_date, lesson_num, student_id, sides_id) values ('2024-01-24', 2, 1, 4);
drop table timetable;
